FROM node:20

# Create app directory
WORKDIR /app

# Install deps first (better layer caching)
COPY package.json package-lock.json* ./

RUN npm install --include=optional

# Copy everything else
COPY . .

# Expose Next dev port
EXPOSE 3000

# Needed for hot reload in Docker
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev"]