FROM node:20

# Create app directory
WORKDIR /app

# Install deps first (better layer caching)
COPY package.json package-lock.json* ./

RUN npm install --include=optional

# Copy everything else
COPY . .

# Expose Next dev port
EXPOSE 3000

CMD ["npm", "run", "dev"]